{% set name = "smokescreen" %}
{% set version = "1.0.0" %}

package:
  name: lsstdesc-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smokescreen-{{ version }}.tar.gz
  sha256: 9e8e97044824ba28675d7893111d1940489b9386e35aaa06f5a006d698be6877

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - astropy >=5.3.0
    - sacc >=0.12
    - pyccl >=3.0.2
    - jsonargparse >=4.0
    - cosmosis >=2.5
    - fitsio
    - firecrown
    - cosmosis-build-standard-library

test:
  imports:
    - smokescreen
  # no pip check since it is broken
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/LSSTDESC/Smokescreen
  summary: 'Smokescreen: DESC Blinding Unified Library. Based on the Muir et al. (2021) data-vector blinding method.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
